apiVersion: v1
kind: ConfigMap
metadata:
  name: studio-config
  namespace: studio
data:
  KC_ASSETS_GIT_URL: "https://github.com/opea-project/GenAIStudio/tree/main/assets/keycloak"
  KEYCLOAK_DNS: "keycloak.studio.svc.cluster.local:8443"
  GRAFANA_DNS: "kube-prometheus-stack-grafana.monitoring.svc.cluster.local"
  STUDIO_FRONTEND_DNS: "studio-frontend.studio.svc.cluster.local:3000"
  APP_FRONTEND_DNS: "app-frontend.$namespace.svc.cluster.local:5175"
  APP_BACKEND_DNS: "app-backend.$namespace.svc.cluster.local:8888"
  PREPARE_DOC_REDIS_PREP_DNS: "prepare-doc-redis-prep-0.$namespace.svc.cluster.local:6007"
  STUDIO_BACKEND_DNS: "studio-backend.studio.svc.cluster.local:5000"