---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-backend-ports-env
data:
  .env: |+
    __PORTS_INFO_JSON_PLACEHOLDER__
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-backend-config
data:
  workflow-info.json: |+
    __BACKEND_PROJECT_INFO_JSON_PLACEHOLDER__
---
apiVersion: v1
kind: Service
metadata:
  name: app-backend
spec:
  type: ClusterIP
  ports:
  - port: 8899
    targetPort: 8899
    protocol: TCP
    name: app-backend
  selector:
    app: app-backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-backend
  labels:
    app: app-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-backend
  template:
    metadata:
      labels:
        app: app-backend
    spec:
      securityContext: null
      containers:
      - name: app-backend
        env:
        - name: USE_NODE_ID_AS_IP
          value: 'true'
        - name: LOGFLAG
          value: 'True'
        __TELEMETRY_ENDPOINT__
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
          seccompProfile:
            type: RuntimeDefault
        image: __APP_BACKEND_IMAGE__
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /tmp
          name: tmp
        - mountPath: /home/user/config/workflow-info.json
          name: workflow-info-volume
          subPath: workflow-info.json
        - mountPath: /home/user/config/.env
          name: ports-env
          subPath: .env
        ports:
        - name: app-backend
          containerPort: 8899
          protocol: TCP
        resources: null
      volumes:
      - name: tmp
        emptyDir: {}
      - name: workflow-info-volume
        configMap:
          name: app-backend-config
      - name: ports-env
        configMap:
          name: app-backend-ports-env
---
apiVersion: v1
kind: Service
metadata:
  name: app-frontend
spec:
  type: ClusterIP
  ports:
  - port: 5275
    targetPort: 80
    protocol: TCP
    name: app-frontend
  selector:
    app: app-frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-frontend
  labels:
    app: app-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-frontend
  template:
    metadata:
      labels:
        app: app-frontend
    spec:
      securityContext: {}
      containers:
      - name: app-frontend
        env:
        # - name: VITE_APP_BACKEND_SERVICE_URL
        #   value: "/v1/app-backend"
        - name: APP_BACKEND_SERVICE_URL
          value: "/v1/app-backend"
        - name: APP_DATAPREP_SERVICE_URL
          value: "/v1/dataprep"
        - name: APP_CHAT_HISTORY_SERVICE_URL
          value: "/v1/chathistory"
        - name: APP_UI_SELECTION
          value: "chat,summary,code"
        __UI_CONFIG_INFO_ENV_PLACEHOLDER__
        securityContext: {}
        image: __APP_FRONTEND_IMAGE__
        imagePullPolicy: Always
        ports:
        - name: ui
          containerPort: 80
          protocol: TCP
        resources: {}
        volumeMounts:
        - mountPath: /tmp
          name: tmp
      volumes:
      - name: tmp
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
      name: mongo
  selector:
    app: mongo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo:7.0.11
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 27017
        command: ["mongod", "--quiet", "--logpath", "/dev/null", "--bind_ip_all"]
---
apiVersion: v1
kind: Service
metadata:
  name: chathistory-mongo
spec:
  type: ClusterIP
  ports:
    - port: 6012
      targetPort: 6012
      protocol: TCP
      name: chathistory-mongo
  selector:
    app: chathistory-mongo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chathistory-mongo
  labels:
    app: chathistory-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chathistory-mongo
  template:
    metadata:
      labels:
        app: chathistory-mongo
    spec:
      containers:
      - name: chathistory-mongo
        image: opea/chathistory-mongo:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6012
        env:
        - name: MONGO_HOST
          value: "mongo"
        - name: MONGO_PORT
          value: "27017"
        - name: COLLECTION_NAME
          value: "Conversations"
        - name: LOGFLAG
          value: "True"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-nginx-config
data:
  default.conf: |+
    # Copyright (C) 2024 Intel Corporation
    # SPDX-License-Identifier: Apache-2.0

    server {
        listen       80;
        listen  [::]:80;

        proxy_connect_timeout 600;
        proxy_send_timeout 600;
        proxy_read_timeout 600;
        send_timeout 600;

        client_max_body_size 10G;

        location /home {
            alias  /usr/share/nginx/html/index.html;
        }

        location / {
            proxy_pass http://app-frontend:5275;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /v1/app-backend {
            proxy_pass http://app-backend:8899;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # Disable buffering for SSE
            proxy_buffering off;
            proxy_cache off;
            proxy_http_version 1.1;
            proxy_set_header Connection '';
            chunked_transfer_encoding off;
        }

        location /v1/chathistory {
            proxy_pass http://chathistory-mongo:6012;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # Disable buffering for SSE
            proxy_buffering off;
            proxy_cache off;
            proxy_http_version 1.1;
            proxy_set_header Connection '';
            chunked_transfer_encoding off;
        }

        __UI_CONFIG_INFO_NGINX_PLACEHOLDER__
    }
---
apiVersion: v1
kind: Service
metadata:
  name: app-nginx
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: app-nginx
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-nginx
  labels:
    app: app-nginx
spec:
  selector:
    matchLabels:
      app: app-nginx
  template:
    metadata:
      labels:
        app: app-nginx
    spec:
      containers:
      - image: nginx:1.27.1
        imagePullPolicy: IfNotPresent
        name: nginx
        volumeMounts:
        - mountPath: /etc/nginx/conf.d
          name: nginx-config-volume
      securityContext: {}
      volumes:
      - configMap:
          defaultMode: 420
          name: app-nginx-config
        name: nginx-config-volume
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: local-path