app-backend:
  image: __APP_BACKEND_IMAGE__
  container_name: app-backend
  volumes:
  - ./workflow-info.json:/home/user/config/workflow-info.json
  - ./.env:/home/user/config/.env
  depends_on:
  __BACKEND_ENDPOINTS_LIST_PLACEHOLDER__
  ports:
  - 8899:8899
  environment:
  - no_proxy=${no_proxy}
  - https_proxy=${https_proxy}
  - http_proxy=${http_proxy}
  - HOST_IP=${public_host_ip}
  ipc: host
  restart: always
app-frontend:
  image: __APP_FRONTEND_IMAGE__
  container_name: app-frontend
  depends_on:
  - app-backend
  ports:
    - 5275:80
  environment:
    - no_proxy=${no_proxy}
    - https_proxy=${https_proxy}
    - http_proxy=${http_proxy}
    - APP_BACKEND_SERVICE_URL=/v1/app-backend
    - APP_DATAPREP_SERVICE_URL=/v1/dataprep
    - APP_CHAT_HISTORY_SERVICE_URL=/v1/chathistory
    - APP_UI_SELECTION=chat,summary,code
    - APP_DEFAULT_UI_TYPE=__DEFAULT_UI_TYPE_PLACEHOLDER__
  ipc: host
  restart: always
app-nginx:
  image: opea/nginx:latest
  container_name: app-nginx
  depends_on:
    - app-frontend
    - app-backend
  ports:
    - 8090:80
  volumes:
    - ./app.nginx.conf.template:/etc/nginx/nginx.conf.template:ro
  environment:
    - no_proxy=${no_proxy}
    - https_proxy=${https_proxy}
    - http_proxy=${http_proxy}
    - FRONTEND_SERVICE_IP=${public_host_ip}
    - FRONTEND_SERVICE_PORT=5275
    - BACKEND_SERVICE_NAME=app-backend
    - BACKEND_SERVICE_IP=${public_host_ip}
    - BACKEND_SERVICE_PORT=8899
    - DATAPREP_SERVICE_IP=${public_host_ip}
    - DATAPREP_SERVICE_PORT=${prepare_doc_redis_prep_0_port:-1234}
  ipc: host
  restart: always