- name: Create ssh keys in k8 secrets using shell and kubectl commands
  hosts: localhost

  tasks:

    - name: Ensure namespace studio exists
      shell: kubectl get ns studio || kubectl create ns studio

    - name: Check if Kubernetes secret exists
      command: kubectl -n studio get secret ssh-keys
      register: kubectl_secret_check
      failed_when: kubectl_secret_check.rc not in [0, 1]
      changed_when: False

    - name: Run Ubuntu pod
      command: |
        kubectl -n studio run ubuntu-ssh-keygen --image=ubuntu --restart=Never -- bash -c "sleep 120"
      register: run_pod
      failed_when: "'created' not in run_pod.stdout and 'already exists' not in run_pod.stderr"
      when: "'NotFound' in kubectl_secret_check.stderr"

    - name: Wait for Ubuntu pod to be ready
      command: kubectl wait --for=condition=Ready pod/ubuntu-ssh-keygen -n studio --timeout=60s
      when: "'NotFound' in kubectl_secret_check.stderr"

    - name: Generate SSH key inside pod
      shell: |
        kubectl exec -n studio ubuntu-ssh-keygen -- bash -c "apt-get update && apt-get install -y openssh-client"
        kubectl exec -n studio ubuntu-ssh-keygen -- bash -c "ssh-keygen -t rsa -b 2048 -f /tmp/id_rsa -N '' -C ''"
      when: "'NotFound' in kubectl_secret_check.stderr"

    - name: Copy ssh keys from pod to local
      shell: |
        kubectl exec -n studio ubuntu-ssh-keygen -- cat /tmp/id_rsa > ./studio-id_rsa && \
        kubectl exec -n studio ubuntu-ssh-keygen -- cat /tmp/id_rsa.pub > ./studio-id_rsa.pub
      when: "'NotFound' in kubectl_secret_check.stderr"

    - name: Create Kubernetes secret from the keys
      command: |
        kubectl -n studio create secret generic ssh-keys \
        --from-file=studio-id_rsa=./studio-id_rsa \
        --from-file=studio-id_rsa.pub=./studio-id_rsa.pub
      when: "'NotFound' in kubectl_secret_check.stderr"

    - name: Cleanup Ubuntu pod and keys
      shell: |
        kubectl delete pod ubuntu-ssh-keygen -n studio 
        rm -f ./studio-id_rsa ./studio-id_rsa.pub
      when: "'NotFound' in kubectl_secret_check.stderr"
