- name: Deploy prometheus and grafana
  hosts: localhost
  tasks:
    - name: Create directory for Prometheus data
      file:
        path: /mnt/data/prometheus
        state: directory
        mode: '0777'
      become: yes

    - name: Create monitoring namespace
      command: kubectl create namespace monitoring
      ignore_errors: yes
    
    - name: Install Helm
      shell: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
    
    - name: Add Prometheus Helm repository
      command: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
    
    - name: Update Helm repositories
      command: helm repo update
    
    # Installing the CRDs needed
    - name: Helm install kube-prometheus-stack
      command: helm install kube-prometheus-stack prometheus-community/kube-prometheus-stack -n monitoring
      ignore_errors: yes
    
    - name: Delete kube-prometheus-stack
      command: helm delete kube-prometheus-stack -n monitoring
      ignore_errors: yes
    
    - name: Apply customized kube-prometheus-stack
      command: kubectl apply -f ../manifests/monitoring-manifest.yaml