# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: Build Images to Registry
permissions: read-all
on:
  workflow_call:
    inputs:
      node:
        required: true
        type: string
      tag:
        default: "latest"
        required: false
        type: string
      test_e2e:
        default: true
        required: false
        type: boolean

jobs:
  build-images:
    runs-on: "docker-build-${{ inputs.node }}"
    steps:
      - name: Clean Up Working Directory
        run: sudo rm -rf ${{github.workspace}}/*

      - name: Print GitHub event
        run: echo '${{ toJson(github.event) }}' | jq '.'
        shell: bash

      - name: Get Checkout Ref
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ] || [ "${{ github.event_name }}" == "pull_request_target" ]; then
          echo "CHECKOUT_REF=refs/pull/${{ github.event.number }}/merge" >> $GITHUB_ENV
          else
            echo "CHECKOUT_REF=${{ github.ref }}" >> $GITHUB_ENV
          fi

      - name: Checkout out Repo
        uses: actions/checkout@v4
        with:
          ref: ${{ env.CHECKOUT_REF }}
          fetch-depth: 0

      - name: Build Image and Push Image
        run: |
            echo ${OPEA_IMAGE_REPO}
            docker login ${OPEA_IMAGE_REPO}
            cd ${{ github.workspace }}/setup-scripts/build-image-to-registry
            ansible-playbook build-image-to-registry.yml -e "container_registry=${OPEA_IMAGE_REPO}opea" -e "container_tag=${{ inputs.tag }}"