# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: Manual - Publish Docker Images
on:
  workflow_dispatch:
    inputs:
      node:
        default: "xeon"
        description: "Hardware to run test"
        required: true
        type: string
      tag:
        default: "rc"
        description: "Tag to publish, like [1.0rc]"
        required: true
        type: string
      publish_tags:
        default: "latest,1.x"
        description: "Tag list apply to publish images, like [latest,1.0]"
        required: false
        type: string

permissions: read-all
jobs:
  publish:
    strategy:
      matrix:
        image: ["studio-frontend", "studio-backend", "app-frontend", "app-backend"]
      max-parallel: 2
    runs-on: "docker-build-${{ inputs.node }}"
    steps:
      - uses: docker/login-action@v3.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Image Publish
        uses: opea-project/validation/actions/image-publish@main
        with:
          local_image_ref: ${OPEA_IMAGE_REPO}opea/${{ matrix.image }}:${{ inputs.tag }}
          image_name: opea/${{ matrix.image }}
          publish_tags: ${{ inputs.publish_tags }}